services:
  mongodb:
    image: mongo:latest
    container_name: dna-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dna-network

  backend:
    build: ./backend
    container_name: dna-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dna_analysis
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - dna-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: dna-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - dna-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

networks:
  dna-network:
    driver: bridge

volumes:
  mongodb_data: