app = "dna-backend"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[build.args]
  PYTHON_VERSION = "3.12"

[env]
  OLLAMA_ENABLED = "true"
  OLLAMA_MODEL = "deepseek-coder:1.5b"
  OLLAMA_API_BASE = "http://localhost:11434"
  MODEL_FALLBACK_PRIORITY = "ollama,deepseek,claude"
  PORT = "8080"
  PYTHONPATH = "/app"
  PYTHON_MODULE = "app.main:app"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "5s"
