[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dna-analysis"
version = "1.0.0"
description = "DNA Analysis API with local-first model architecture"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["app"]
