[project]
name = "dna-backend"
version = "0.1.0"
description = "DNA Analysis Backend"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "requests",
    "python-dotenv"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
